# Generated by Django 3.2.4 on 2021-06-11 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('tag', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=200)),
                ('img_s1', models.CharField(max_length=200)),
                ('img_s2', models.CharField(max_length=200)),
                ('img_s3', models.CharField(max_length=200)),
                ('os', models.CharField(max_length=50)),
                ('processor', models.CharField(max_length=50)),
                ('memory', models.CharField(max_length=50)),
                ('graphics', models.CharField(max_length=50)),
                ('directX', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=50)),
                ('video', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
