# Generated by Django 3.2.4 on 2021-06-11 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20210611_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='list_date',
        ),
    ]
