# Generated by Django 3.2.4 on 2021-06-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20210611_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='img_s1',
            new_name='index',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='img_s2',
            new_name='inner_img1',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='img_s3',
            new_name='inner_img2',
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='listing',
            name='inner_img3',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
