# Generated by Django 3.2.4 on 2021-06-12 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20210612_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='description',
        ),
    ]
