# Generated by Django 3.2.4 on 2021-06-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_listing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
