game_type = {
    'Action':'動作',
    'Horror':'恐怖',
    'Comedy':'歡樂',
    'Assassin':'暗殺',
    'Arcade':'街機',
    'Fighting':'格鬥',
    'Violent':'暴力',
    'Platformer':'平台',
    'Sniper':'狙擊手',
    'Gore':'血腥',
    'FPS':'第一人稱射擊',
    'Shooter':'射擊',
    'Stealth':'潛行',
    '2D':'2D',
    'Adventure':'冒險',
    '2D Fighter':'2D 格鬥',
    'Open World':'開放世界',
    'Survival Horror':'生存恐怖',
    "Beat 'em up":'帶狀卷軸動作',
    'Roguelike':'類 Rogue',
    'Action-Adventure':'動作冒險',
    'Hack and Slash':'砍殺',
    'Warhammer 40K':'戰錘40K',
    'Action RPG':'動作角色扮演',
    'Souls-like':'類魂系列',
    'World War II':'二戰',
    'Casual':'休閒',
    'eSports':'電競',
    'Strategy':'策略',
    'Side Scroller':'橫向卷軸',
    'Survival':'生存',
    'RPG':'角色扮演',
    'Singleplayer':'單人',
    'Post-apocalyptic':'末日之後',
    'Zombies':'喪屍',
    'Story Rich':'劇情豐富',
    'Sci-fi':'科幻'
}

game_price = {
    0:'免費',
    500:'500元以下',
    1000:'1000元以下',
    1500:'1500元以下',
    2000:'2000元以下',
    3500:'3500元以下',
    4000:'4000元以下',
}